"""made artist name unique

Revision ID: 34713886aa30
Revises: 1626b225ca2b
Create Date: 2020-03-14 21:07:21.343322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34713886aa30'
down_revision = '1626b225ca2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_unique_constraint('artist_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint('artist_name', type_='unique')

    # ### end Alembic commands ###
