"""removed artist website unique constraint

Revision ID: f8ce90ec8532
Revises: 6c5e22a81bd9
Create Date: 2020-03-25 19:27:22.760175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ce90ec8532'
down_revision = '6c5e22a81bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artists_website_key', 'artists', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('artists_website_key', 'artists', ['website'])
    # ### end Alembic commands ###
